### ISSUE TITLE
Will the trained model be released?

### ISSUE THREAD

**Issue by wustone1995** [trinhvg/IMPash#1]
Great job and thanks for sharing the code! Will the trained model be released?

**Comment by trinhvg** [comment]
Sure! I will upload it and let you know when it is ready shortly. Thank you for your interested in our work!

**Comment by trinhvg** [comment]
IMPaSh weights have been uploaded, and both the encoder and classifier checkpoint. Please check the Readme to find the links.

**Comment by mztom3745** [comment]
Thank you for your work, but I noticed that the uploaded checkpoint has expired. Could you please re-upload it? I would be very grateful.

**Comment by trinhvg** [comment]
> Thank you for your work, but I noticed that the uploaded checkpoint has expired. Could you please re-upload it? I would be very grateful.

Hello, I updated the link. Please check it again and let me know if there are any issues accessing it.

**Comment by mztom3745** [comment]
> > Thank you for your work, but I noticed that the uploaded checkpoint has expired. Could you please re-upload it? I would be very grateful.
> 
> Hello, I updated the link. Please check it again and let me know if there are any issues accessing it.


Thank you very much, but I have a question: In your readme document, you mentioned using the command “python main_contrast_Jig.py” to train the self-supervised encoder. However, there is only “main_contrast.py” in the folder. Similarly, I couldn’t find the “main_linear_9sra.py” file mentioned in the readme document when training the classifier and options. Are these two files “main_contrast.py” and “main_linear.py” in the folder, or do I need to input some other instructions to generate them?

**Comment by trinhvg** [comment]
> Thank you very much, but I have a question: In your readme document, you mentioned using the command “python main_contrast_Jig.py” to train the self-supervised encoder. However, there is only “main_contrast.py” in the folder. Similarly, I couldn’t find the “main_linear_9sra.py” file mentioned in the readme document when training the classifier and options. Are these two files “main_contrast.py” and “main_linear.py” in the folder, or do I need to input some other instructions to generate them?

Hi, I didn't clean the code, so it looks quite messy here.  “main_contrast.py" and   “main_linear.py” are the correct ones. You are welcome to go head and use them.
Otherwise, you can come back next week; I will clean the code this weekend. 
Cheers,
